### ISSUE TITLE
running orangemeow/matrix-archive:1.2 in docker keeps hanging after ~100 events (msg,images)

### ISSUE THREAD

**Issue by PatrickJRed** [MeowOrange/matrix-archive#1]
I am running orangemeow/matrix-archive:1.2 in docker (version 20.10.12) on Lubuntu 20.04.3 LTS.

I run it like this:

docker run -it --name mwa -v "/PATH/element-keys.txt:/matrix_archive/key.txt" -v "/PATH/chats:/matrix_archive/chats" -e "SERVER=https://..." -e "USER=@...:..." -e "USERPASS=..." -e "KEYPASS=..." -e "ROOMSTR=--room $RID" orangemeow/matrix-archive:1.2

($RID is set by Bash within a for-loop - the rest is correct as it does work)

The Rooms have over 400 messages and images per day.

I tried to archive a Room with more than 4000 images and msg but your programm keeps hanging - it manages to archive around 100 msg/images before i have to kill and restart it (good thing it continues rather than re-archive everything).

FYI i dont have the logs (due to the way my script works)

**Comment by MeowOrange** [comment]
I'm sorry that I can't reproduce this issue, but here's what I think.

This is the workflow of my script:

1. Fetch all events into memory. This includes all text messages, message id, media url but without media contents. 

    This step works good in your situation because otherwise there won't be any following procedures.

2. For every event, check if it's already in database, if not:

    2.1. If the event does not contain media content, format it and save into database. This is totally processed locally. I don't think there will be any "hanging" problem.

    2.2. If the event contains media content, download that media into memory, decrypt it, hash it, and de-duplicate by comparing hash with hashes in database.

There are 2 possible problems: database and network. But since you're running it in docker, and a container won't run twice and trigger a concurrent write SQLite issue, so I prefer that you're having a download timeout issue. The SDK I based on(Matrix-Nio) does not have a timeout option for download media method, so it may cause hanging in my script. 

I have updated my script to tag:1.3. SDK is updated and Python requests library is used to download media files. If there is more download timeouts, after a few retries exceptions will be raised.

**Comment by PatrickJRed** [comment]
Okay, Thx,

Let me try out the new version.

**Comment by PatrickJRed** [comment]
I now have a cronjob running its container (via bash-script)
Can/Did you implement some form of return/status codes: e.g.
0 => succes
1 => timeout in download
2 => failure with sql
A logfile feature (in which your script would redirect stdout and stderr would be nice)

**Comment by MeowOrange** [comment]
Ok I just updated the script, added log output and exit code, see [README.md](https://github.com/MeowOrange/matrix-archive/blob/main/README.md) for details

**Comment by PatrickJRed** [comment]
Though some Media it refueses/gets an error like
{"errcode":"M_NOT_FOUND","error":"Not found [...]"}
but that my be cause it ot deleted - idk
