### ISSUE TITLE
feature request : having media filenames with custom scheme instead of uuid - media-filename templated

### ISSUE THREAD

**Issue by PatrickJRed** [MeowOrange/matrix-archive#2]
i find the way that the script generates a uuid as filename for the media good:

i would prefere the media-files to have a schemed-name
%DATE-OF-UPLOAD%_%TIME-OF-UPLOAD%_%UPLOAD-USER-ENCODED%.%EXT% --> e.g. 2021-12-20_15-30_@myuser:matrix.org.png for a png that was uploaded on 20th dec. 2021 at 3:30 pm
this would allow me to search for my pictures more easly. (or just search for a specific image)
because currently i cannot do that

%UPLOAD-USER-ENCODED% : @%USER%:%HOMESERVER%

**Comment by PatrickJRed** [comment]
https://github.com/MeowOrange/matrix-archive/blob/main/utils.py :
def generate_uuid1():

**Comment by MeowOrange** [comment]
I see what you mean but sorry I did this on purpose. Also, I don't suggest you doing this on your own.

My script has a de-duplication procedure. For example:

user sent **a.jpg** in 2022-01-20
user sent **b.jpg** in 2022-02-20

**a.jpg** is identical to **b.jpg**, so only one of them should be kept. Now my script keeps the earlier one, name it with uuid, and point the second event to uuid.jpg. If name the files with %DATE-OF-UPLOAD%, you will not be able to find 20220220.jpg because it's deleted for duplication.

In fact, what you want to do(search media files in certain date/time interval) is possible even for the current version:

1. Take a look at chats/room_id/**data.db**, in table MESSAGES there is all events, including media messages. You can search however you want.

    I recommand you a sqlite database viewer - [Antares](https://antares-sql.app/). The following screenshot demenstrates how to use Antares to search media files in database.

    If you want to do this on your phone, you can either find a phone app supporting SQLite3 or use a dockerized [CloudBeaver](https://hub.docker.com/r/dbeaver/cloudbeaver) to setup a webpage to do that.

![Snipaste_2022-03-27_09-41-28](https://user-images.githubusercontent.com/54757137/160263051-cfb112d0-546f-44f4-9735-13a6fb1b2971.png)



2. My script downloads media files in the same order as events, which means the media files' Date Modified is in the same order as the dates they are sent. You can just sort the media folder by Date Modified and that shows you which media is earlier, which is later.

**Comment by PatrickJRed** [comment]
You know what.
I am going to write an webapp (php,js,html,css) that uses your script to download everything
1) then analyze the db
2) get uuid,... and generate new filenames via the filenamescheme (and symlinks for duplicates)
3) rename the UUID-files to the generated ones

**Comment by PatrickJRed** [comment]
This way i can use symlinks and restructure your filesystem-structure (chat/ROOMID to chat/HUMANREADABLEROOMNAME)
